name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d --build

  database:

    steps:    
    - name: Create database
      run: docker-compose run web rake db:create
      
    - name: Prepare database
      run: docker-compose run web rake db:migrate db:test:prepare

  tests:
      
    steps:
    - name: Run tests
      run: docker-compose run web bundle exec rspec test/models/auction_test.rb

    - name: Simplecov Report
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
